name = input("enter your name:")
age = int(input("enter your age:"))
city = input("enter yout city:")
Skills = input("enter your Skills:")
print(5*"="+"PROFILE"+5*"=")
print("Name:",name)
print("Age:",age)
print("City:",city)
print("Skills:",Skills)
print(17*"=")
